variables:
  - group: AssetsManager
  - name: 'vmImageName'
    value: 'ubuntu-latest'
  - name: 'serviceConnectionName'
    value: 'Azure'
  - name: 'project'
    value: 'AssetsManager'

resources:
  pipelines:
    - pipeline: ci
      source: 'AssetsManager CI'
      trigger: true

pool:
  vmImage: $(vmImageName)

pr:
  branches:
    include: ['dev']
  paths:
    include:
      - 'src/*'
      - 'infrastructure/*'
      - 'tests/*'

trigger: none

stages:
  - stage: Integration
    displayName: Integration
    jobs:
      - template: ./templates/backend-stage-azure.yml
        parameters:
          VmImage: $(vmImageName)
          Environment: Integration
          StageShort: int
          ServiceConnectionName: $(serviceConnectionName)
          ProjectName: $(project)
          DeployBicep: false
          StatusState: 'Waiting'
          StatusDescription: 'CD is waiting for test stage approval'
          Sites:
            - name: 'api-DD-$(project)-core'
              package: 'Services.CoreApi.zip'
              net: 8
            - name: 'ui-DD-$(project)'
              package: 'Ui.NextApp-INTEGRATION.zip'
              node: '18-lts'
              healthCheckPath: "api/health"

  - stage: Test
    displayName: Test
    jobs:
      - template: ./templates/backend-stage-azure.yml
        parameters:
          VmImage: $(vmImageName)
          Environment: Test
          StageShort: test
          ServiceConnectionName: $(serviceConnectionName)
          ProjectName: $(project)
          DeployBicep: false
          StatusState: 'Waiting'
          StatusDescription: 'CD is waiting for production stage approval'
          Sites:
            - name: 'api-DD-$(project)-core'
              package: 'Services.CoreApi.zip'
              net: 8
            - name: 'ui-DD-$(project)'
              package: 'Ui.NextApp-TEST.zip'
              node: '18-lts'
              healthCheckPath: "api/health"

  - stage: Production
    displayName: Production
    jobs:
      - template: ./templates/backend-stage-azure.yml
        parameters:
          VmImage: $(vmImageName)
          Environment: Production
          StageShort: prod
          ServiceConnectionName: $(serviceConnectionName)
          ProjectName: $(project)
          DeployBicep: false
          StatusState: 'Succeeded'
          StatusDescription: 'CD successfully deployed to production'
          Sites:
            - name: 'api-DD-$(project)-core'
              package: 'Services.CoreApi.zip'
              net: 8
            - name: 'ui-DD-$(project)'
              package: 'Ui.NextApp-PRODUCTION.zip'
              node: '18-lts'
              healthCheckPath: "api/health"
