namespace devdeer.AssetsManager.Data.Entities.Entities.Base
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    using devdeer.Libraries.Abstractions.Interfaces;

    /// <summary>
    /// Abstract base class for all entities.
    /// </summary>
    public abstract class BaseEntity : IEntity
    {
        #region explicit interfaces

        /// <summary>
        /// The unique ID generated by the database.
        /// </summary>
        [Key]
        [Column(nameof(Id), Order = 1)]
        public long Id { get; set; }

        #endregion
    }
}